### ISSUE TITLE
Move API key to server

### ISSUE THREAD

**Issue by cgatian** [BrycePearce/WhenDoesItAir#4]
https://github.com/BrycePearce/WhenDoesItAir/blob/80e3f0837fb585a4ea0ebfa7260660ec2c3c479c/client/src/app/services/task.service.ts#L22

It might be a good idea to have the server proxy these requests so your API key is kept hidden

**Comment by BrycePearce** [comment]
Originally I had this call on the back-end, but I ended up moving it to the front-end on this commit:

https://github.com/BrycePearce/WhenDoesItAir/commit/9c5caf7764d3904f276275b129c5668b72feea5d

This was because the TMDB api does rate limits based on user IP, and I would quickly hit my request limit, since every request on the back-end was coming from one IP. 

So I ended up moving it to the front, so that each user would not be restricted based on the site activity.

I'm open to any other solutions you might have though, I agree that displaying api keys is not good practice.

If you have an idea, please feel free to open up another ticket.
